### ISSUE TITLE
AD0001 InvalidOperationException @ EmptyCollectionsShouldNotBeEnumerated

### ISSUE THREAD

**Issue by nnpcYvIVl** [SonarSource/sonar-csharp#1005]
```Severity           Code   Description     Project File      Line     Suppression State      Detail Description
Warning          AD0001           Analyzer 'SonarAnalyzer.Rules.CSharp.EmptyCollectionsShouldNotBeEnumerated' threw an exception of type 'System.InvalidOperationException' with message 'This operation does not apply to an empty instance.'.          CCM                1          Active  Analyzer 'SonarAnalyzer.Rules.CSharp.EmptyCollectionsShouldNotBeEnumerated' threw the following exception:
'Exception occurred with following context:
Compilation: CCM
SyntaxTree: D:\My Documents\Visual Studio 2017\AppLibrary\AppLibrary\AppLibrary.cs
SyntaxNode: internal static string ByteArrayToBase64String ... [MethodDeclarationSyntax]@[301311..301573) (6651,8)-(6659,9)

System.InvalidOperationException: This operation does not apply to an empty instance.
   at System.Collections.Immutable.ImmutableStack`1.Peek()
   at SonarAnalyzer.SymbolicExecution.ProgramState.PopValue(SymbolicValue& poppedValue)
   at SonarAnalyzer.Rules.CSharp.EmptyCollectionsShouldNotBeEnumerated.EmptyCollectionAccessedCheck.<>c__DisplayClass15_0.<GetArgumentSymbolicValues>b__0(ArgumentSyntax argument)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.Aggregate[TSource,TAccumulate](IEnumerable`1 source, TAccumulate seed, Func`3 func)
   at SonarAnalyzer.Rules.CSharp.EmptyCollectionsShouldNotBeEnumerated.EmptyCollectionAccessedCheck.RemoveCollectionConstraintsFromArguments(ArgumentListSyntax argumentList, ProgramState programState)
   at SonarAnalyzer.Rules.CSharp.EmptyCollectionsShouldNotBeEnumerated.EmptyCollectionAccessedCheck.ProcessInvocation(ProgramState programState, InvocationExpressionSyntax invocation)
   at SonarAnalyzer.Rules.CSharp.EmptyCollectionsShouldNotBeEnumerated.EmptyCollectionAccessedCheck.PreProcessInstruction(ProgramPoint programPoint, ProgramState programState)
   at SonarAnalyzer.SymbolicExecution.CSharpExplodedGraph.<>c__DisplayClass3_0.<VisitInstruction>b__0(ProgramState ps, ExplodedGraphCheck check)
   at SonarAnalyzer.SymbolicExecution.CSharpExplodedGraph.<>c__DisplayClass4_0.<InvokeChecks>b__0(ProgramState ps, ExplodedGraphCheck check)
   at System.Linq.Enumerable.Aggregate[TSource,TAccumulate](IEnumerable`1 source, TAccumulate seed, Func`3 func)
   at SonarAnalyzer.SymbolicExecution.CSharpExplodedGraph.InvokeChecks(ProgramState programState, Func`3 invoke)
   at SonarAnalyzer.SymbolicExecution.CSharpExplodedGraph.VisitInstruction(ExplodedGraphNode node)
   at SonarAnalyzer.SymbolicExecution.AbstractExplodedGraph.Walk()
   at SonarAnalyzer.Rules.CSharp.EmptyCollectionsShouldNotBeEnumerated.CheckForEmptyCollectionAccess(CSharpExplodedGraph explodedGraph, SyntaxNodeAnalysisContext context)
   at SonarAnalyzer.SymbolicExecution.FlowAnalysisExtensions.Analyze(CSharpSyntaxNode declarationBody, ISymbol symbol, Action`2 analyze, SyntaxNodeAnalysisContext context)
   at SonarAnalyzer.SymbolicExecution.FlowAnalysisExtensions.<>c__DisplayClass0_0.<RegisterExplodedGraphBasedAnalysis>b__1(SyntaxNodeAnalysisContext c)
   at SonarAnalyzer.Helpers.DiagnosticAnalyzerContextHelper.<>c__DisplayClass0_0`1.<RegisterSyntaxNodeActionInNonGenerated>b__0(SyntaxNodeAnalysisContext c)
   at SonarAnalyzer.Helpers.SonarAnalysisContext.<>c__DisplayClass16_0`1.<RegisterSyntaxNodeAction>b__0(SyntaxNodeAnalysisContext c)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.<>c__43`1.<ExecuteSyntaxNodeAction>b__43_0(ValueTuple`2 data)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock[TArg](DiagnosticAnalyzer analyzer, Action`1 analyze, TArg argument, Nullable`1 info)
-----
'.```

**Comment by Evangelink** [comment]
Duplicates of #1002
