### ISSUE TITLE
Fix S101: Rule should not throw IndexOutOfRangeException

### ISSUE THREAD

**Issue by nnpcYvIVl** [SonarSource/sonar-csharp#1006]
```Severity	Code	Description	Project	File	Line	Suppression State	Detail Description
Warning	AD0001	Analyzer 'SonarAnalyzer.Rules.CSharp.ClassAndMethodName' threw an exception of type 'System.IndexOutOfRangeException' with message 'Index was outside the bounds of the array.'.	WMIHangTest		1	Active	Analyzer 'SonarAnalyzer.Rules.CSharp.ClassAndMethodName' threw the following exception:
'Exception occurred with following context:
Compilation: WMIHangTest
SyntaxTree: C:\Download\WMIHangTest\WMIHangTest\Form1.cs
SyntaxNode: Thread thread.  [MethodDeclarationSyntax]@[356..372) (16,8)-(17,0)

System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at System.Text.StringBuilder.get_Chars(Int32 index)
   at SonarAnalyzer.Rules.CSharp.ClassAndMethodName.IsMemberNameValid(String identifierName, String& suggestion)
   at SonarAnalyzer.Rules.CSharp.ClassAndMethodName.CheckMemberName(MemberDeclarationSyntax member, SyntaxToken identifier, SyntaxNodeAnalysisContext context)
   at SonarAnalyzer.Rules.CSharp.ClassAndMethodName.<>c.<Initialize>b__10_0(SyntaxNodeAnalysisContext c)
   at SonarAnalyzer.Helpers.DiagnosticAnalyzerContextHelper.<>c__DisplayClass0_0`1.<RegisterSyntaxNodeActionInNonGenerated>b__0(SyntaxNodeAnalysisContext c)
   at SonarAnalyzer.Helpers.SonarAnalysisContext.<>c__DisplayClass16_0`1.<RegisterSyntaxNodeAction>b__0(SyntaxNodeAnalysisContext c)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.<>c__43`1.<ExecuteSyntaxNodeAction>b__43_0(ValueTuple`2 data)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock[TArg](DiagnosticAnalyzer analyzer, Action`1 analyze, TArg argument, Nullable`1 info)
-----
'.```

**Comment by Evangelink** [comment]
Hi @nnpcYvIVl,

I have some trouble reproducing the error (this rule is actually quite big and there are a couple of places were this error could happen). Would you mind sharing with us some code reproducing the issue?

Cheers,
Amaury
