### ISSUE TITLE
AD0001 - NullReferenceException - Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by valhristov** [SonarSource/sonar-csharp#1389]
### Description

AD0001 warning

```
SyntaxNode: await AppLib.SQLRunQueryAsync(new ... [AwaitExpressionSyntax]@[3450..3579) (89,24)-(89,153)

System.NullReferenceException: Object reference not set to an instance of an object.
   at SonarAnalyzer.Rules.CSharp.ParameterValidationInMethodShouldBeWrapped`1.<>c.<Initialize>b__6_3(SyntaxNodeWithSymbol`2 tuple)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at SonarAnalyzer.Rules.CSharp.ParameterValidationInMethodShouldBeWrapped`1.<Initialize>b__6_0(SyntaxNodeAnalysisContext c)
   at SonarAnalyzer.Helpers.DiagnosticAnalyzerContextHelper.<>c__DisplayClass0_0`1.<RegisterSyntaxNodeActionInNonGenerated>b__0(SyntaxNodeAnalysisContext c)
   at SonarAnalyzer.Helpers.SonarAnalysisContext.<>c__DisplayClass21_0`1.<RegisterContextAction>b__0(TContext c)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.<>c__43`1.<ExecuteSyntaxNodeAction>b__43_0(ValueTuple`2 data)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock[TArg](DiagnosticAnalyzer analyzer, Action`1 analyze, TArg argument, Nullable`1 info)
----- 
```

### Repro steps

Compile project

* SonarLint for VS Version - 4.0.0.3479
* Visual Studio Version (e.g. Professional v15.4.1) - v15.7.0
* Languages in your solution (C#, VB.Net, Javascript, C, C++) C#

**Comment by valhristov** [comment]
@usmrtester I moved https://github.com/SonarSource/sonarlint-visualstudio/issues/646 here, as the bug is in the static analyzer.
