### ISSUE TITLE
S3963 crashes

### ISSUE THREAD

**Issue by xperiandri** [SonarSource/sonar-csharp#564]
### Description

```
Warning	AD0001	Analyzer 'SonarAnalyzer.Rules.CSharp.InitializeStaticFieldsInline' threw an exception of type 'System.NullReferenceException' with message 'Object reference not set to an instance of an object.'.	Data		1	Active	Analyzer 'SonarAnalyzer.Rules.CSharp.InitializeStaticFieldsInline' threw the following exception:
'Exception occurred with following context:
Compilation: Data
SyntaxTree: src\Data\Repositories\CarRepository.cs
SyntaxNode: static CarRepository() => cars = ... [ConstructorDeclarationSyntax]@[587..2728) (27,8)-(83,14)

System.NullReferenceException: Object reference not set to an instance of an object.
   at SonarAnalyzer.Rules.CSharp.InitializeStaticFieldsInline.<>c.<Initialize>b__5_0(SyntaxNodeAnalysisContext c)
   at SonarAnalyzer.Helpers.DiagnosticAnalyzerContextHelper.<>c__DisplayClass0_0`1.<RegisterSyntaxNodeActionInNonGenerated>b__0(SyntaxNodeAnalysisContext c)
   at SonarAnalyzer.Helpers.SonarAnalysisContext.<>c__DisplayClass12_0`1.<RegisterSyntaxNodeAction>b__0(SyntaxNodeAnalysisContext c)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.<>c__43`1.<ExecuteSyntaxNodeAction>b__43_0(ValueTuple`2 data)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock[TArg](DiagnosticAnalyzer analyzer, Action`1 analyze, TArg argument, Nullable`1 info)
-----
'.
```
### Repro steps

Try this file. Created from ASP.NET Core Boilerplate API template.
Just create a new project with `dotnet new bapi` using [this manual](https://github.com/ASP-NET-Core-Boilerplate/Templates#how-can-i-get-it)

``` C#
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Models;

namespace Repositories
{
    public interface ICarRepository
    {
        Task<Car> Add(Car car);

        Task Delete(Car car);

        Task<Car> Get(int carId);

        Task<ICollection<Car>> GetPage(int page, int count);

        Task<int> GetTotalPages(int count);

        Task<Car> Update(Car car);
    }

    public class CarRepository : ICarRepository
    {
        private static readonly List<Car> cars;

        static CarRepository()
        {
            cars = new List<Car>()
            {
                new Car()
                {
                    CarId = 1,
                    Created = DateTimeOffset.UtcNow.AddDays(-8),
                    Cylinders = 8,
                    Make = "Lambourghini",
                    Model = "Countach",
                    Modified = DateTimeOffset.UtcNow.AddDays(-8)
                },
                new Car()
                {
                    CarId = 2,
                    Created = DateTimeOffset.UtcNow.AddDays(-7),
                    Cylinders = 10,
                    Make = "Mazda",
                    Model = "Furai",
                    Modified = DateTimeOffset.UtcNow.AddDays(-6)
                },
                new Car()
                {
                    CarId = 3,
                    Created = DateTimeOffset.UtcNow.AddDays(-7),
                    Cylinders = 6,
                    Make = "Honda",
                    Model = "NSX",
                    Modified = DateTimeOffset.UtcNow.AddDays(-3),
                },
                new Car()
                {
                    CarId = 4,
                    Created = DateTimeOffset.UtcNow.AddDays(-5),
                    Cylinders = 6,
                    Make = "Lotus",
                    Model = "Esprit",
                    Modified = DateTimeOffset.UtcNow.AddDays(-3),
                },
                new Car()
                {
                    CarId = 5,
                    Created = DateTimeOffset.UtcNow.AddDays(-4),
                    Cylinders = 6,
                    Make = "Mitsubishi",
                    Model = "Evo",
                    Modified = DateTimeOffset.UtcNow.AddDays(-2),
                },
                new Car()
                {
                    CarId = 6,
                    Created = DateTimeOffset.UtcNow.AddDays(-4),
                    Cylinders = 12,
                    Make = "McLaren",
                    Model = "F1",
                    Modified = DateTimeOffset.UtcNow.AddDays(-1),
                }
            };
        }

        public Task<Car> Add(Car car)
        {
            cars.Add(car);
            car.CarId = cars.Max(x => x.CarId) + 1;
            return Task.FromResult(car);
        }

        public Task Delete(Car car)
        {
            if (cars.Contains(car))
            {
                cars.Remove(car);
            }

            return Task.FromResult(0);
        }

        public Task<Car> Get(int carId)
        {
            var car = cars.FirstOrDefault(x => x.CarId == carId);
            return Task.FromResult(car);
        }

        public Task<ICollection<Car>> GetPage(int page, int count)
        {
            var pageCars = cars
                .Skip(count * (page - 1))
                .Take(count)
                .ToList();
            if (pageCars.Count == 0)
            {
                pageCars = null;
            }

            return Task.FromResult((ICollection<Car>)pageCars);
        }

        public Task<int> GetTotalPages(int count)
        {
            var totalPages = (int)Math.Ceiling(cars.Count / (double)count);
            return Task.FromResult(totalPages);
        }

        public Task<Car> Update(Car car)
        {
            var existingCar = cars.FirstOrDefault(x => x.CarId == car.CarId);
            existingCar.Cylinders = car.Cylinders;
            existingCar.Make = car.Make;
            existingCar.Model = car.Model;
            return Task.FromResult(car);
        }
    }
}
```

### Expected behavior

Code fix is available and works

### Actual behavior

Exception is thrown and no code fix appear

### Related information

* SonarC# 6.1.0.2359
* Visual Studio 15.3.0 Preview 4

**Comment by Evangelink** [comment]
Hi @xperiandri!

I have just tried to create the MyTemplate project as described in your link. I have manually installed SonarAnalyzer.CSharp nuget (6.2), I have added a ruleset file with only S3963 and rebuilt the solution. I can see the warning but I cannot reproduce the exception.

Could you try with the new version? Also could you tell me if you have manually installed the NuGet as I did or if you went through another technique? The connected mode doesn't work as it is a dotnet core project and in the standalone mode the rule is not active by default.
