### ISSUE TITLE
The 'SonarLintDaemonPackage' did not load correctly

### ISSUE THREAD

**Issue by shadow-cs** [SonarSource/sonar-csharp#654]
### Description

SonarLint fails to initialize properly after update.

Not sure how general this problem is but this is the second time I'm getting the following error after updating SonarLint package:

`The 'SonarLintDaemonPackage' did not load correctly.`

Additionally `ActivityLog.xml` contains following error message:

```
SetSite failed for package [SonarLintDaemonPackage]Source: 'PresentationCore' Description: The calling thread must be STA, because many UI components require this. System.InvalidOperationException: The calling thread must be STA, because many UI components require this.
at System.Windows.Input.InputManager..ctor()
at System.Windows.Input.InputManager.GetCurrentInputManagerImpl()
at System.Windows.Input.KeyboardNavigation..ctor()
at System.Windows.FrameworkElement.FrameworkServices..ctor()
at System.Windows.FrameworkElement.EnsureFrameworkServices()
at System.Windows.FrameworkElement..ctor()
at System.Windows.Controls.Control..ctor()
at System.Windows.Window..ctor()
at SonarLint.VisualStudio.Integration.Vsix.SonarLintDaemonPackage.InitializeAsync(CancellationToken cancellationToken, IProgress`1 progress)
at Microsoft.VisualStudio.Shell.AsyncPackage.<>c__DisplayClass16_0.<<Microsoft-VisualStudio-Shell-Interop-IAsyncLoadablePackageInitialize-Initialize>b__1>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at Microsoft.VisualStudio.Services.VsTask.RethrowException(AggregateException e)
at Microsoft.VisualStudio.Services.VsTask.InternalGetResult(Boolean ignoreUIThreadCheck)
at Microsoft.VisualStudio.Services.VsTask.GetResult()
```

SonarLint appears to continue working despite the error.

### Known workarounds

Delete the VS profile from `AppData`.

### Related information

* SonarC# 3.4.0.1732
* Visual Studio 15.2

**Comment by Evangelink** [comment]
Duplicate https://github.com/SonarSource/sonarlint-visualstudio/issues/243
