### ISSUE TITLE
Fix S2325: 'Member should be static' throws NullReferenceException

### ISSUE THREAD

**Issue by ilyalukinykh** [SonarSource/sonar-csharp#819]
`MemberShouldBeStatic` rule throws `System.NullReferenceException` for this class.

```
public class Class
{
    public async Task<Result<T> Function<T>(Func<Task<Result<T>>> f)
    {
        Result<T> result;
        result = await f();
        return result;
    }
}
```

The result is `System.NullReferenceException`: 

```
Warning	AD0001	Analyzer 'SonarAnalyzer.Rules.CSharp.MemberShouldBeStatic' threw an exception of type 'System.NullReferenceException' with message 'Object reference not set to an instance of an object.'.	Library		1	Active	Analyzer 'SonarAnalyzer.Rules.CSharp.MemberShouldBeStatic' threw the following exception:
'Exception occurred with following context:
Compilation: Library
SyntaxTree: _.cs
SyntaxNode: await f(); [MethodDeclarationSyntax]@[4082..4092) (108,21)-(108,31)

System.NullReferenceException: Object reference not set to an instance of an object.
   at SonarAnalyzer.Rules.CSharp.MemberShouldBeStatic.GetMethodDescendants(MethodDeclarationSyntax methodDeclaration)
   at SonarAnalyzer.Rules.CSharp.MemberShouldBeStatic.CheckIssue[TDeclarationSyntax](SyntaxNodeAnalysisContext context, Func`2 getDescendants, Func`2 getIdentifier, String memberKind)
   at SonarAnalyzer.Rules.CSharp.MemberShouldBeStatic.<Initialize>b__6_2(SyntaxNodeAnalysisContext c)
   at SonarAnalyzer.Helpers.DiagnosticAnalyzerContextHelper.<>c__DisplayClass0_0`1.<RegisterSyntaxNodeActionInNonGenerated>b__0(SyntaxNodeAnalysisContext c)
   at SonarAnalyzer.Helpers.SonarAnalysisContext.<>c__DisplayClass12_0`1.<RegisterSyntaxNodeAction>b__0(SyntaxNodeAnalysisContext c)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.<>c__DisplayClass42_1`1.<ExecuteSyntaxNodeAction>b__1()
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock(DiagnosticAnalyzer analyzer, Action analyze, Nullable`1 info)
-----
'.
```

It's not a false positive alert, since the input is not a valid code. However, such an unhandled exception make sonar stuck until process restarted.

**Comment by michalb-sonar** [comment]
Thank you for reporting and sample crashing code @ilyalukinykh, that is very helpful! We are able to reproduce the problem and will address it.
