### ISSUE TITLE
Rule MemberShouldBeStatic throws NullReferenceException

### ISSUE THREAD

**Issue by Evangelink** [SonarSource/sonar-csharp#902]
From @RalfKoban 

Hi, I just met that issue.

```
Severity	Code	Description	Project	File	Line	Suppression State	Detail Description
Error	AD0001	Analyzer 'SonarAnalyzer.Rules.CSharp.MemberShouldBeStatic' threw an exception of type 'System.NullReferenceException' with message 'Object reference not set to an instance of an object.'.	MiKo Aspects		1	Active	Analyzer 'SonarAnalyzer.Rules.CSharp.MemberShouldBeStatic' threw the following exception:
'Exception occurred with following context:
Compilation: MiKoSolutions.Aspects
SyntaxTree: D:\Private\MiKo Solutions\MiKo Aspects\Source\MiKo Aspects\Internals\Extensions\ReflectionExtensions.cs
SyntaxNode: Compile(); [MethodDeclarationSyntax]@[16871..16881) (354,74)-(354,84)

System.NullReferenceException: Object reference not set to an instance of an object.
   at SonarAnalyzer.Rules.CSharp.MemberShouldBeStatic.GetMethodDescendants(MethodDeclarationSyntax methodDeclaration)
   at SonarAnalyzer.Rules.CSharp.MemberShouldBeStatic.CheckIssue[TDeclarationSyntax](SyntaxNodeAnalysisContext context, Func`2 getDescendants, Func`2 getIdentifier, String memberKind)
   at SonarAnalyzer.Rules.CSharp.MemberShouldBeStatic.<Initialize>b__6_2(SyntaxNodeAnalysisContext c)
   at SonarAnalyzer.Helpers.DiagnosticAnalyzerContextHelper.<>c__DisplayClass0_0`1.<RegisterSyntaxNodeActionInNonGenerated>b__0(SyntaxNodeAnalysisContext c)
   at SonarAnalyzer.Helpers.SonarAnalysisContext.<>c__DisplayClass16_0`1.<RegisterSyntaxNodeAction>b__0(SyntaxNodeAnalysisContext c)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.<>c__43`1.<ExecuteSyntaxNodeAction>b__43_0(ValueTuple`2 data)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock[TArg](DiagnosticAnalyzer analyzer, Action`1 analyze, TArg argument, Nullable`1 info)
```

The source code that produces the exception is a nested class in an extension class:

        /// <summary>
        /// Provides a mechanism to create <see cref="Delegate"/>s based on <see cref="MethodInfo"/>s via <see cref="Expression"/> trees.
        /// </summary>
        private static class DelegateCreator
        {
            [Pure]
            public static Delegate Create(MethodInfo method)
            {
                var instance = Expression.Parameter(method.DeclaringType, "instance");
                var arguments = CreateParameterExpressions(method);
                var body = CreateBodyExpression(method, instance, arguments);
                return Expression.Lambda(body, instance.Including(arguments)).Compile();
            }

            [Pure]
            private static Expression CreateBodyExpression(MethodInfo method, Expression instance, ParameterExpression[] arguments)
            {
                Expression methodCall = Expression.Call(instance, method, arguments);
                return method.ReturnType == typeof(void) ? methodCall : Expression.Convert(methodCall, method.ReturnType);
            }

            [Pure]
            private static ParameterExpression[] CreateParameterExpressions(MethodInfo method)
            {
                var parameters = method.GetParameters();
                var arguments = new ParameterExpression[parameters.Length];
                for (var i = 0; i < arguments.Length; i++)
                {
                    var parameter = parameters[i];
                    arguments[i] = Expression.Parameter(parameter.ParameterType, parameter.Name);
                }

                return arguments;
            }
        }

**Comment by Evangelink** [comment]
Hi @ralfkoban,
Could you let us know which version of SonarC# you are using? If the bug appears under SonarLint for VS, which version of VS and which version of SonarLint?

I cannot reproduce the bug locally with latest version on your code.

**Comment by Evangelink** [comment]
It seems like this issue duplicates #819
