### ISSUE TITLE
Intermittently failing project analysis: Plugin [csharp] does not exist

### ISSUE THREAD

**Issue by Vossekop** [SonarSource/sonar-csharp#922]
Hi there,

I have a clean installation of SonarQube 6.7 LTS with the 6.5.0.3766 version of the csharp plugin, although I have also tried the latest (6.6.0.3969) with similar results: My VSTS builds fail most of the time with a timeout error message on finalizing SonarQube Analysis.

After investigation, i noticed in SQ errors in the background tasks that are supposed to do the analysis I presume. The errors are always the same:

java.lang.IllegalArgumentException: Plugin [csharp] does not exist
	at org.sonar.ce.container.CePluginRepository.getPluginInfo(CePluginRepository.java:95)
	at org.sonar.server.computation.task.projectanalysis.step.LoadReportAnalysisMetadataHolderStep.getBasePluginKey(LoadReportAnalysisMetadataHolderStep.java:132)
	at org.sonar.server.computation.task.projectanalysis.step.LoadReportAnalysisMetadataHolderStep.lambda$loadQualityProfiles$1(LoadReportAnalysisMetadataHolderStep.java:127)
	at java.util.stream.Collectors.lambda$toMap$58(Unknown Source)
	at java.util.stream.ReduceOps$3ReducingSink.accept(Unknown Source)
	at java.util.Iterator.forEachRemaining(Unknown Source)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Unknown Source)
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source)
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.util.stream.ReferencePipeline.collect(Unknown Source)
	at org.sonar.server.computation.task.projectanalysis.step.LoadReportAnalysisMetadataHolderStep.loadQualityProfiles(LoadReportAnalysisMetadataHolderStep.java:125)
	at org.sonar.server.computation.task.projectanalysis.step.LoadReportAnalysisMetadataHolderStep.execute(LoadReportAnalysisMetadataHolderStep.java:88)
	at org.sonar.server.computation.task.step.ComputationStepExecutor.executeSteps(ComputationStepExecutor.java:64)
	at org.sonar.server.computation.task.step.ComputationStepExecutor.execute(ComputationStepExecutor.java:52)
	at org.sonar.server.computation.task.projectanalysis.taskprocessor.ReportTaskProcessor.process(ReportTaskProcessor.java:75)
	at org.sonar.ce.taskprocessor.CeWorkerImpl.executeTask(CeWorkerImpl.java:134)
	at org.sonar.ce.taskprocessor.CeWorkerImpl.findAndProcessTask(CeWorkerImpl.java:97)
	at org.sonar.ce.taskprocessor.CeWorkerImpl.withCustomizedThreadName(CeWorkerImpl.java:81)
	at org.sonar.ce.taskprocessor.CeWorkerImpl.call(CeWorkerImpl.java:73)
	at org.sonar.ce.taskprocessor.CeWorkerImpl.call(CeWorkerImpl.java:43)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

Also, see the attached file for the scanner context.
[ScannerContext.txt](https://github.com/SonarSource/sonar-csharp/files/1461938/ScannerContext.txt)

Is this a known issue? Any work arounds or fixes?

Kind regards,

Jeroen

**Comment by Evangelink** [comment]
Hi @Vossekop,

It seems like your issue is not related to the plugin itself but could be a bug on SonarQube side. Would you mind opening a new thread on the [SonarQube Google Group](https://groups.google.com/forum/#!forum/sonarqube)?

Thanks,
Amaury
